name: a_salon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
<<<<<<< Updated upstream
  sdk: ^3.5.1
=======
  sdk: ^3.5.2
>>>>>>> Stashed changes

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
