name: a_salon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.0
  flutter_rating_bar: ^4.0.0
  http: ^1.0.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
assets:
    - lib/asset/reservasi.png
    - lib/asset/reservasiAktif.png
    - lib/asset/layanan.jpg
    - lib/asset/1.jpg
    - lib/asset/2.jpg
    - lib/asset/3.jpg
    - lib/asset/4.jpg