name: a_salon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.0
  camera: ^0.10.5+2
  image_picker: ^0.8.4+8
  mobile_scanner: ^3.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/asset/logo putih.png
    - lib/asset/logo biru.png
    - lib/asset/layanan.jpg
    - lib/asset/promo 1.jpg
    - lib/asset/promo 2.jpg